---
title: "Results 2022"
author: "Michael Rustler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Results 2022}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

## Men

### Grundschule

```{r men_g}
men_g <- minimarathon::get_results("M", ak_class = "G")
DT::datatable(men_g,
              rownames = FALSE)

```

### Oberschule

```{r men_o}
men_o <- minimarathon::get_results("M", ak_class = "O")
DT::datatable(men_o)

```

### Sonderwertung

```{r men_s}
men_s <- minimarathon::get_results("M", ak_class = "SO")
DT::datatable(men_s)

```


## Women

### Grundschule

```{r women_g}
women_g <- minimarathon::get_results("W", ak_class = "G")
DT::datatable(women_g)

```
### Oberschule

```{r women_o}
women_o <- minimarathon::get_results("W", ak_class = "O")
DT::datatable(women_o)

```

### Sonderwertung

```{r women_s}
women_s <- minimarathon::get_results("W", ak_class = "SO")
DT::datatable(women_s)

```
)
